---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

version: '3.7'

services:
  wpad:
    build:
      context: '.'
    image: 'mireiawen/wpad:latest'
    restart: 'unless-stopped'
    hostname: '$HOSTNAME.$DOMAIN'
    container_name: 'wpad'
    networks:
    - 'traefik'
    labels:
    - 'traefik.enable=true'
    - 'traefik.http.routers.wpad.rule=Host(`$HOSTNAME.$DOMAIN`)'
    - 'traefik.http.routers.wpad.entrypoints=web'
    - 'traefik.http.routers.wpad.middlewares=ipwhitelist@file,http-to-https@file'
    - 'traefik.http.routers.wpad.service=wpad'
    - 'traefik.http.routers.wpad-secure.rule=Host(`$HOSTNAME.$DOMAIN`)'
    - 'traefik.http.routers.wpad-secure.entrypoints=websecure'
    - 'traefik.http.routers.wpad-secure.middlewares=ipwhitelist@file'
    - 'traefik.http.routers.wpad-secure.service=wpad'
    - 'traefik.http.services.wpad.loadbalancer.passhostheader=true'
    - 'traefik.http.services.wpad.loadbalancer.server.port=80'

networks:
  traefik:
    external: true
